### ISSUE TITLE
SVNLookError

### ISSUE THREAD

**Issue by 0sudash9** [jasperlee108/svndumpfilterIN#32] opened 2017-01-15 08:31 UTC
#I have 60 gigs dump file from which i gotta filter only the TRUNK. While running the filter command i encountered the below issue. Can someone help fix this issue?

Node-copyfrom-rev: 15912 is in skipped revisions, trying to untangle
Warning: svnlook is required to pull missing files

__main__.SVNLookError: svnlook: Can't open file 'srp\TRUNK\format': The system cannot find the path specified.

Command used : 
svndumpfilter.py input.dump include trunk /TRUNK/DEV -d --repo=srp/TRUNK/ -o output.dump

PS: the original "trunk" folder was deleted and after changing many paths is currently named as "TRUNK" . Hence included both paths

**Comment by freeamac** [comment] 2017-01-17 01:39
The message means that the svnlook utility is not in your path.  It needs
to be in your path when you execute svndumpfilter.py as it is used to parse
out source which comes from a different branch or directory location.

On linux you should be able to do a "which svnlook" to see if it is in your
path (usually it will be in the same location as "svn").

http://svnbook.red-bean.com/en/1.7/svn.ref.svnlook.html

**Comment by 0sudash9** [comment] 2017-01-18 11:18
Hi Freemac,
Thanks for identifying the root cause. But I request to provide more details. 
Below is the setup we have in the SVN server and we are running SVN on windows 2003.

We use collabnet subversion and the **svnlook.exe** utility is under the collabnet subversion directory where all other commands(svnadmin, svndumpfilter etc) are also available.

we have svn repository directory separately(outside collabnet subversion directory) where the "revisions" are maintained in the **db** directory.

Can you pls advise what should I do now to ensure svnlook in under the repository path?
I placed the utility directly in the repo path but it didn't quite work as expected, I got the same error.

**Comment by freeamac** [comment] 2017-01-19 06:45
It does not need to be a specific folder location but available in your
execution path. So where ever you are running svndumpfiler.py from, when
you type in "svnlook" on the command line, do you get a response?

btw what is the command line you are typing in to filter the dump file?

I don't have access to a Windows machine so my ability to provide a lot of
guidance is going to be limited.

**Comment by 0sudash9** [comment] 2017-01-19 11:06
Yes I do get a response from svnlook command when I run svnlook help from the path where I run the filter.

Here is the command used  
svndumpfilter.py <input.dump> include trunk /TRUNK/DEV -d --repo=srp/TRUNK/ -o <output.dump>
Path 1 = trunk
Path 2 = /TRUNK/DEV

**Comment by freeamac** [comment] 2017-01-19 23:02
Sorry I may have been misled by making an assumption on what the issue was.

The warning is a normal message (although it should only occur once, but
that may be a display bug).

What then is the end failure when you run svndumpfiler.py on your dump file?

**Comment by 0sudash9** [comment] 2017-01-20 06:49
**Node-copyfrom-rev: 15912 is in skipped revisions, trying to untangle
Warning: svnlook is required to pull missing files

main.SVNLookError: svnlook: Can't open file 'srp\TRUNK\format': The system cannot find the path specified.**

This is what I get before the script ends.

Let me clearly explain the folder structure we have in SVN to help troubleshoot better.

Initially, as general practice the main project was housed under SVN trunk.
**trunk
 -project folder**

In subsequent years the "trunk" was re-named and copied to different paths and at present the structure is like below 

**TRUNK
  -DEV
      - Project folder**

There are 160K revisions in total and the current TRUNK was added at around 86K revsion, we should be good even if we can retain history from around 86K till the latest.

I also tried with START REVISION parameter that the script offers, but I believe it still starts dumping from the 1st revision and exits around 15K mark.

**Comment by freeamac** [comment] 2017-01-23 06:48
You should be able to add '--debug' as an option which should print out the
exact svnlook command that is being executed which appears to be the cause
of the failure.

It probably will look like "svnlook -r 15912 cat srp/TRUNK/"

Can you execute the svnlook command from the debug information successfully
on the command line? If that fails, you may not be able perform the filter

Can you filter using the native svndumpfilter command? If not, why? If
there is an error what is it?

Getting deeper into the issue will require the meta data of revision 15912
extracted from the dump file and also the revision which is calling the
node copyfrom

**Comment by Knitschi** [comment] 2020-09-15 15:47
I have the same problem. The "format" file that is mentioned in the error message seems not to be in the repository. At least when looking at it with the TortoiseSVN repository browser. Is this a special svn file?

**Comment by Knitschi** [comment] 2020-09-15 16:16
My error was that I used

```
svndumpfilter.py ... -r https://myserver/svn/repo ...
```
the svnlookup command is supposed to be run on the svn server and expects paths on the filesystem. So assuming that you have a network share for the repository directory you can run

```
svndumpfilter.py ... -r \\myserver\svn\repo ...
```

This worked for me. Running the script on the svn server should also work.

**Comment by freeamac** [comment] 2024-03-06 00:03
Indeed it needs to be run on the hosting server

**Closed** 2024-03-06 00:03 UTC
