### ISSUE TITLE
OverflowError Python int too large for c long

### ISSUE THREAD

**Issue by TobiasBreuer** [jasperlee108/svndumpfilterIN#34] opened 2017-09-27 10:27 UTC
I just tried the latest version for filtering a dump of our repository. Note that the dump of the original repo has a size of 221 GB and contains some more than 70k commits (The filtered dump has grown to 39 GB when the error occurred).

When running svndumpfilterIn on this dump to extract a specific path for a new repository with untangling active, at some point in time it will crash with this information:

`Adding revision 66982 to the skipped revisions list`
`---- Working on Input Revision 66983 (Renumber Rev: 28342) ----`
`---- Working on Input Revision 66984 (Renumber Rev: 28343) ----`
`Traceback (most recent call last):`
`  File "svndumpfilter.py", line 961, in <module>`
`    main()`
`  File "svndumpfilter.py", line 956, in main`
`    parse_dump(input_dump, opt.output_dump, matches, include, opt)`
`  File "svndumpfilter.py", line 807, in parse_dump`
`    node_seg.extract_segment(input_file)`
`  File "svndumpfilter.py", line 322, in extract_segment`
`    self._extract_body(d_file)`
`  File "svndumpfilter.py", line 314, in _extract_body`
`    self.body = d_file.read(int(self.head[TEXT_CONTENT_LEN]))`
`OverflowError: Python int too large to convert to C long`

If anyone has any idea how to solve or circumvent this issue, please let me know.

**Update**
I took a closer look at the revision **66984** within the db\revs folder of the source repository. It turns out that this revision itself has a size of **9.5 GB**. Somebody obviously committed a hole lot of huge binary stuff. Can I somehow exclude this exact revision using the filter?

Thanks and best regards,

Tobias

**Comment by MattInDC** [comment] 2018-03-06 00:15
I am having this same problem, also with a large but much smaller commit (242 MB). Has anyone found a workaround?

Thanks,
-- Matt

**Comment by TobiasBreuer** [comment] 2018-03-06 06:15
@MattInDC I ended up, writing a small tool that gets rid of the problematic revisions by reading the dump file byte per byte and removing the content (not the header-meta information) of the problematic revisions.
After that I was able to run the svndumpfilter without any problem.
**Note however** that this hacky workaround only is valid if those problematic revisions are really independent (i.e. the rest of the history is not relying on parts of those revisions). In my case luckily this was the case.

**Comment by MattInDC** [comment] 2018-03-06 14:46
Thanks @TobiasBreuer... That may work for me - I'll need to review the history. In this case I think someone committed a database backup to the repo, so I can probably eliminate it. The issue is whether there are additional revisions that depend on it.

**Comment by freeamac** [comment] 2024-03-08 00:55
One way to look for problematically long contents in the dump file prior to filtering:

```
$ grep -a Text-content-length <dump_file>| sort -nr | head
Text-content-length: 767
Text-content-length: 381
Text-content-length: 15
```

With the update of svndumpfilterIN to python 3 where and int no longer has a max value, this should not be an issue provided there are enough machine resources to read the content into memory

**Closed by freeamac** 2024-03-08 00:55 UTC
